### ISSUE TITLE
Convert GATK vcf file to .vcf "standard"

### ISSUE THREAD

**Issue by VeronicaGlez** [VeronicaGlez/Red_warbler_repo#11]
The [dataset](https://github.com/VeronicaGlez/Red_warbler_repo/tree/main/data) that I use in this repository was downloaded from [Dryad](https://datadryad.org/stash/dataset/doi:10.5061/dryad.kb610)   and is the same datased from the work ***"Plumage genes and little else distinguish the genomes of hybridizing warblers".*** This data set was work with the GATK software and in theory the Gvcf works same. The difference is just that the Gvcf has additional information like variant record and non-variant record) [see GVCF](https://gatk.broadinstitute.org/hc/en-us/articles/360035531812-GVCF-Genomic-Variant-Call-Format) .
The problem occurs when I try to transform the gvcf to plink or Structure format and I run the ADMIXTURE or fastStructure programs, it gives me an error.
 Therefore, I want to change the gvcf to vcf (in standard format) to see if it affects the additional information to run the analyzes. 

I tried to convert Gvcf file with vcftools, PGDSpider to vcf or o plink but doesn't work (for SNPRelate tha dataset works).

When run fastStrucute the error:

	python structure.py -K 1 --input=structure2 --format=str --full --seed=100 --output=k1
	Traceback (most recent call last):
	 File "structure.py", line 172, in <module>
	    G = parse_str.load(params['inputfile'])
 	 File "parse_str.pyx", line 10, in parse_str.load
  	  L = loci.shape[1]
	IndexError: tuple index out of range

In admixture:

	for K in 1 2 3 4 5 6; do  ./admixture --cv=6 warbler.bed $K | tee log${K}.out; done

Error
Cross-validation will be performed.  Folds=6.
Random seed: 43
Point estimation method: Block relaxation algorithm
Convergence acceleration algorithm: QuasiNewton, 3 secant conditions
Point estimation will terminate when objective function delta < 0.0001
Estimation of standard errors disabled; will compute point estimates only.
Invalid chromosome code!  Use integers.

**Comment by bgrueda** [comment]
Maybe you could explore your file, the chromosome column, to see if all are integers because of: "Invalid chromosome code! Use integers", if you have strings, that could be a problem.

with:
 `awk '{print $1}' file | sort | uniq`   
you could see the text chains in the first column and look if they are integers or not.

**Comment by redgcko7** [comment]
I found this thread in biostars for scripts to change chromosome numbers:
https://www.biostars.org/p/98582/

`awk '{gsub(/_random/,""); print}' your.vcf > no_chr.vcf`

**Comment by VeronicaGlez** [comment]
Select Chrom

`awk '{print $1}' data_warbler.vcf | sort | uniq`
```
1
10
10_random
11
11_random
12
12_random
13
13_random
14
14_random
15
15_random
17
17_random
18
18_random
19
19_random
1A
1A_random
1B
1_random
2
20
20_random
21
21_random
22
22_random
23
23_random
24
25
25_random
26
26_random
27
28
28_random
2_random
3
3_random
4
4A
4A_random
4_random
5
5_random
6
6_random
7
7_random
8
8_random
9
9_random
Un
Z
Z_random
```

**Comment by redgcko7** [comment]
code for combining several changes to your chromosome numbers in the same line of code (from the same Biostars thread as above):

`awk '{gsub(/_random/, ""); gsub(/1A/, "1"); gsub(/Z/, "0"); print;}' original.vcf > original_newchr.vcf`

**Comment by VeronicaGlez** [comment]
Line run
`awk '{gsub(/_random/, ""); gsub(/1A/, "1"); gsub(/4A/,"4");  gsub(/Z/, "0"); gsub(/Un/,"-99"); gsub(/1B/,"1"); print;}' data_warbler.vcf > data_warbler_newchr.vcf`

**Comment by bgrueda** [comment]
You could try to change the *"-99"* for *"99"* instead of have just positive numbers

**Comment by redgcko7** [comment]
In the Structure google group, it seems that people with this error have resolved it by removing the header row, which would have to be done in the .str or .bed file, not the .vcf:
https://groups.google.com/g/structure-software/c/dZ_84e0R-UE/m/a35jiMChCwAJ

**Comment by redgcko7** [comment]
to ignore extra chromosomes in plink(https://www.biostars.org/p/369469/):
Add the "--allow-extra-chr" (or "--aec" for short) flag to permit these codes in the input

**Comment by bgrueda** [comment]
There are some ways to convert *.vcf* to *plink*

https://www.researchgate.net/post/Coverting-vcf-files-to-plink-bed-format

**Comment by VeronicaGlez** [comment]
We change the .bim file, we change the  chromosom names:

`awk '{gsub(/_random/, ""); gsub(/1A/, "1"); gsub(/4A/,"4"); gsub(/Z/, "0"); gsub(/Un/,"99"); gsub(/1B/,"1"); gsub(/LGE22/,"0"); print }' warbler.bim > data_warbler_newchr2.bim
`
 Additionally: we rename the plink file names
```
cp warbler.bed data_warbler_newchr2.bed
cp warbler.fam data_warbler_newchr2.fam
```
And finally, we run admixture:
`for K in 1 2 3 4 5 6; do  ./admixture --cv=6 data_warbler_newchr2.bed $K | tee log${K}.out; done`


Yeeeeei :D   :D
