### ISSUE TITLE
Create a function to summarize means of genetics estimates 

### ISSUE THREAD

**Issue by VeronicaGlez** [VeronicaGlez/Red_warbler_repo#19]
I want to create a function for summarize means for different genetic estimates (Observed heterozygosity, expected heterozygosity and Inbreeding) and make a data frame with all them for each population ("BRWA"	"BWWA"	"GWWA").
Now, I have different datasets with this estimates (Ho,He,Fis) for each locus (16104 SNPs)  to 3 phenotypes.
Script:
```
#Script for genetic analysis

library("hierfstat")

#load dataset
yw <-read.delim("../data/SNPs_012.012", sep = "\t", header = FALSE, na.strings = -1)

#delete first column
yw <- yw[,-1]
class(yw)

#Replace format 012 by 2 digits 
yw[yw==0] <- 55
yw[yw==1] <- 56
yw[yw==2] <- 66

#load metadata
meta <- read.delim("../meta/met_yw.csv", sep = ",")

#merge phenotypes with database
yw2 <- cbind(meta$phenotype, yw)
yw2<- as.data.frame(yw2)

##basic statistics of genetic (by phenotype)
aa <-basic.stats(yw2, diploid = T)

# Observed heterozygosity(Ho)
Pob <- levels(meta$phenotype)
Ho <-numeric(0)
Ho.locus <- aa$Ho
write.table(Ho.locus, file = "../out/Ho.txt", sep = "\t")

#expected heterozygosity(He)
Hs <-numeric(0)
Hs.locus <- aa$Hs
write.table(Hs.locus, file = "../out/Hs_locus.txt", sep = "\t")

#inbreeding 
Fis <- numeric(0)
Fis.locus <- aa$Fis
Fis.locus[is.na(Fis.locus)] <- 0
write.table(Fis.locus, file = "../out/Fis_yw.txt", sep = "\t")

#merge genetics data
statis <- cbind(Ho.locus, Hs.locus, Fis.locus)
write.table(statis, file = "../out/genetic_summary.txt", sep = "\t")
```
Each output (He,Ho,FIS) looks like:
```

"BRWA"	"BWWA"	"GWWA"
"V2"	0	0.1154	0.0385
"V3"	0	0.0741	0.028
"V4"	0	0.0741	0.0278
"V5"	0.125	0.4167	0.2727
"V6"	0	0	0.0531
"V7"	0.4444	0.3571	0.1982
"V8"	0.1111	0.0833	0.0583
"V9"	0	0.1333	0.0411
"V10"	0	0.125	0.0417
...
"V16104"	
```
And I want a data frame with something like:
  ```
      "BRWA"    "BWWA"  "GWWA"
Ho    * 	 *  	*
He    * 	 *  	*
FIS   * 	 *  	*

```
*mean value

**Comment by valeriafloral** [comment]
I found this function **summarySE** that summarizes the mean and sd, it needs the library `dplyr`:

```
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=TRUE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  
  
  return(datac)
}
```


Then you can call the function for each column:

```
rta <- summarySE(tabla_E2, measurevar="TA", groupvars= "Cepa")
rta
```

And it return and output like this:

![image](https://user-images.githubusercontent.com/59807620/105369406-22c73700-5bc8-11eb-864e-2d6dcd6aeb1e.png)

**Comment by camillethuyentruong** [comment]
[Here](https://stackoverflow.com/questions/26209092/how-to-do-in-r-a-loop-that-calculate-mean-and-median-of-rows-and-add-it-in-a-dat) is an example that can serve you.

**Comment by camillethuyentruong** [comment]
The function `colMeans`automatically calculate the mean of all colums in a table. See [here](https://www.statology.org/calculate-mean-multiple-columns-in-r/) for more details

**Comment by bgrueda** [comment]
This could be useful for merging the tables.
https://stackoverflow.com/questions/1299871/how-to-join-merge-data-frames-inner-outer-left-right

`merge(table, table2, by = "Common column")`

I think that there are 2 forms, merging the tables before the colMeans function or once you have the results to put it together in the same table. Maybe is better merge before.

**Comment by camillethuyentruong** [comment]
It is probably better to join all tables together first. The package [dplyr](https://rpubs.com/williamsurles/293454) is a great tool to manipulate tables. 
Otherwise in bash you can easily call multiple files inside a loop!

**Comment by camillethuyentruong** [comment]
Another option is to create a list of all your tables using `sapply` or [`lapply`](https://www.guru99.com/r-apply-sapply-tapply.html#2)
Example [here](https://stackoverflow.com/questions/40383967/create-and-use-different-tables-in-for-loops-in-r-in-a-shorter-way)

**Comment by VeronicaGlez** [comment]
```
new <- merge(meta1, meta4, by=NULL)
```
this command kill my computer jajaja.
The issue was resolve with:
```
#load metadata
meta1 <- read.delim("../out/Ho.txt", sep = "\t")
meta4 <- read.delim("../out/Fis_yw.txt", sep = "\t")


Ho <- colMeans(na.omit(meta1))
fis <- colMeans(na.omit(meta4))
summary <- cbind(Ho,fis)
write.table(summary, file = "../out/summary.txt")
```

            Ho        fis
BRWA 0.1500002 0.04400679
BWWA 0.1698881 0.05020939
GWWA 0.1563188 0.12614610

:D!!

But, when we have a lots dataframes can be more difficult, maybe we can use bash or diplyr

                                                       Will be continue....

**Comment by valeriafloral** [comment]
I couldn't run the summarySE function because the data.frame is not arranged in the same way, so I've tried  to make a large data frame:

```
#Import the table and add a FIS extra column
FIS1 <- read.delim("Fis_yw.csv", sep = ",")
FIS <- data.frame(append(FIS, c(x1='FIS'), after=0))
Ho1 <- read.delim("Ho.csv", sep = ",")
Ho <- data.frame(append(Ho1, c(x1='Ho'), after=0))


#Remane the estimates columns
names(all)[names(all) == "x1"] <- "Estimate"

#Merge the tables
all <- bind_rows(FIS, Ho)
all$Estimate <- as.character(all$Estimate)
```

Then you can call the function

```
SummaryBRWA <- summarySE(all, measurevar="BRWA", groupvars= "Estimate")
SummaryBRWA
```

and have a table like this:

![image](https://user-images.githubusercontent.com/59807620/105380941-0fba6400-5bd4-11eb-9a9a-c691fd71d2ad.png)

**Comment by camillethuyentruong** [comment]
Here is a simple solution

```
# Create three tables
value1 = c(1,3,4)
value2 = c(2,4,6)
value3 = c(3,3,4)

data1 = cbind(value1,value2,value3)
data2 = cbind(value3,value2,value1)
data3 = cbind(value2,value3,value1)

# Join the tables in a list
mylist <- list(data1,data2,data3)
mylist

# Calling colMeans (that calculate the mean for each colum of a table) for each table of the list
sapply(mylist, colMeans)
```

 [,1]     [,2]     [,3]
value1 2.666667 3.333333 4.000000
value2 4.000000 4.000000 3.333333
value3 3.333333 2.666667 2.666667
