### ISSUE TITLE
Change legends of PCA abbreviation to species

### ISSUE THREAD

**Issue by VeronicaGlez** [VeronicaGlez/Red_warbler_repo#9]
In this part I explorer my warbler's data set [data_warbler.vcf](https://github.com/VeronicaGlez/Red_warbler_repo/tree/main/data) ; with SNPRelate and ggplot packages, I made a PCA with 2 warbler's species (BRWA blue-winged warbler, Vermivora pinus; BWWA golden-winged warbler, Vermivora chrysoptera) and a hybrid ( Brewster's warbler hybrid), to assess if there is any structure between the species and the hybrid with this script  [1_exploratorios_pca.R](https://github.com/VeronicaGlez/Red_warbler_repo/blob/main/bin/1_exploratorios_pca.R) :
```

#plot PCA
p <- ggplot(pca_data, aes(x=EV2, y=EV1))+
  geom_point(aes(color=phenotype)) +
theme(legend.title = element_text(size=13))+
  theme(legend.text = element_text(size = 12))+
  xlab(paste0("Eigenvector 2 explaining ", round(pc.percent, 2)[2], "%")) +
ylab(paste0("Eigenvector 1 explaining ", round(pc.percent, 2)[1], "%"))
p
```

![pca_phenotype](https://user-images.githubusercontent.com/17887504/99319026-731fc280-282e-11eb-8d33-2cb0e290a8a8.png)

However, it is difficult to know what abbreviations of the common name mean, I hope to change the legends by the name of each species.

**Comment by VeronicaGlez** [comment]
I found this function for change labs and legends
```
# Modify legend titles
p + labs(colour = "Species" )
p + scale_color_manual(name="Species", 
                        labels = c("Vermivora pinus", 
                                   "Vermivora crysoptera", 
                                   "Brewster's warbler hybrid"), 
                        values = c("BRWA"="blue", 
                                   "BWWA"="red", 
                                   "GWWA"="black")) 
```




![pca](https://user-images.githubusercontent.com/17887504/99326302-addd2700-283d-11eb-9488-7a9c9798bf58.png)

but the colors are sooo ugly!!! How I can  conserve the past colors, and only change names??

**Comment by VeronicaGlez** [comment]
I found this command for change the labels:
```
p + labs(fill = "Species")
p +   scale_color_discrete(limits = c("Vermivora pinus", "Vermivora crysoptera", "Brewster's warbler hybrid"))
```
![pca_problem](https://user-images.githubusercontent.com/17887504/99327358-5f308c80-283f-11eb-90d0-915f45360d7f.png)

but I lost the colors of pca :(

**Comment by VeronicaGlez** [comment]
```
p + scale_color_manual(name="Species", 
                        labels = c("Vermivora pinus", 
                                   "Vermivora crysoptera", 
                                   "Brewster's warbler hybrid"), 
                        values = c("BRWA"="blue", 
                                   "BWWA"="red", 
                                   "GWWA"="orange")
```

**Comment by AliciaMstt** [comment]
Legend ggplot2 help http://www.cookbook-r.com/Graphs/Legends_(ggplot2)/

**Comment by VeronicaGlez** [comment]
We used `scale_color_discrete` for change legends:
```
p + scale_color_discrete(name="Species",
                         breaks=c("BRWA", "BWWA", "GWWA"),
                         labels=c("Vermivora pinus", "Vermivora crysoptera", "Warbler hybrid"))
```

Yeeei Issue resuelto!!! :D
